spring.application.name=api-explorer
server.port=8080

# Cluster name -> OpenShift console login URL
openshift.clusters.rm3.console-url=https://console-openshift-console.apps.rm3.7wse.p1.openshiftapps.com
