spring.application.name=openshift-ui
server.port=8081

openshift.clusters.rm3.console-url=https://console-openshift-console.apps.rm3.7wse.p1.openshiftapps.com

spring.config.import=optional:file:./application-local.properties
